typography_spectrum: 0
color:
  brandColors:
    - '#FF6700'
    - '#EBEBEB'
    - '#C0C0C0'
    - '#3A6EA5'
    - '#004E98'
  brandStrength: 0.3125
  lightness: 1
  saturation: 0.5
  rhythmicContrast: 0.5
opengraph:
  image: null
  type: null
  appId: null
layout_spectrum: 0.25103
analytics:
  google: null
  facebook: null
  twitter: null
name: marthamena
cta:
  domain: null
  bucket: null
  version: null
favicon: null
title: 'Martha Mena '
purpose: []
